language: php
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: 0QUSwsDmlmauj5pjSY9B1Ng6qpDYQiBPvWi6Wk5lZeezHBHVfsTWe0Jhy+yIBCxdnJ2djAgUj0+8eu3gAOg4aIRIS4DxFX37XzDwban9Wfuj5MYxYdCxMGZQq0NtFOOLnqPyb+DHk7JQyy6WPmIOkFv0S+scBfJlcInkPphX5DTNdUjnAFL0VpZhZETkLY6segingNHhVQl4Glw00g9SfW8H0gXH8LgxfquvKFN+AFFgqvzcWjvoXBa36BKHXaR5H5CRw+18JULvCAUSkkanmUnF0028z1sr5i297TbFdZxgYAS43SY3IOEPVSBj4HPMHKbgN7xT3DAMcAI+cIyDKwK2VcMnUef7QPSUM0iO+ldZvMRkmXvjlPWTr/c0zreNNZsU1QxgHoICIDcuiyPxzvXrNjlH8u/Xzhr0862+lOyuyPvbChppNuoWQZoeGgKe4ncdD0imhl+Ry7ITjL6n0KBE9JVm0Z5/Hn2dCRNa/rYh3lqZcYauCBGDaJp3JyCfsM7mvNep4wz60x1j9k5Yj3KaAYrf1r5nZM4KeK9wX25vxYAEI12pafo3WfQL+qk0dqVayV8FpQNyV23YN/bxWr6obn/+YRq+rwF6zwN4UBnEj5dHrTc/UFV3IYpjrUgtLvaCtkv84ewqUCf3NU4EDzCoYThWkOGkALvgP1Z6TYY=
branches:
  only:
  - master
php:
- 5.6
- 7.0
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=3.9 WP_MULTISITE=0
- WP_VERSION=4.7 WP_MULTISITE=0
matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- |
  if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
    composer global require "phpunit/phpunit=5.6.*"
  else
    composer global require "phpunit/phpunit=4.8.*"
  fi
- |
  composer global require wp-coding-standards/wpcs
  phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
script:
- phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
- phpunit
